# -*- coding: utf-8 -*-
"""HeartDiseasePredictionApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139mLhLpFMKo0aBq6ZAtvI3Y_lXnpZhWo
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!pip install kaggle

!kaggle datasets download -d redwankarimsony/heart-disease-data -p /content/heart-disease-data --unzip --force

import pandas as pd
df = pd.read_csv('/content/heart-disease-data/heart_disease_uci.csv')

df.head()

print(df.columns)

df.isnull().sum()

numeric_cols=df.select_dtypes(include='number').columns
df[numeric_cols]=df[numeric_cols].fillna(df[numeric_cols].mean())

import numpy as np
# Add a target column (replace with actual target if you have it)
np.random.seed(42)
df['target'] = np.random.randint(0, 2, size=len(df))

# Separate features and target
X = df.drop('target', axis=1)
y = df['target']

print("Features shape:", X.shape)
print("Target distribution:\n", y.value_counts())

import seaborn as sns
import matplotlib.pyplot as plt

df[numeric_cols].hist(figsize=(15,10))
plt.tight_layout()
plt.show()

sns.heatmap(df[numeric_cols].corr(),annot=True,cmap='coolwarm')
plt.title('Numeric Feature Correlations')
plt.show()

# Identify categorical columns
cat_cols = X.select_dtypes(include='object').columns.tolist()
print("Categorical columns:", cat_cols)



print(df.columns)

X=df.drop('num',axis=1)
y=(df['num']>0).astype(int)



"""# **Advanced Models and Feature Engineering**

### **Train/test Split , Normalization ,Modelling and Model Evaluation**
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

X_train , X_test, y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# Identify numeric and categorical columns
numeric_cols = X.select_dtypes(include='number').columns.tolist()
categorical_cols = X.select_dtypes(exclude='number').columns.tolist()

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ]
)

# Fit and transform training data
X_train_scaled = preprocessor.fit_transform(X_train)
X_test_scaled = preprocessor.transform(X_test)

print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

from sklearn.linear_model import LogisticRegression   #for classification



lr_model = LogisticRegression()
lr_model.fit(X_train_scaled,y_train)

"""Model Evaluation"""

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

y_pred_lr = lr_model.predict(X_test_scaled)
print("Logistic Regression Accuracy:",accuracy_score(y_test,y_pred_lr))
print(classification_report(y_test,y_pred_lr))

"""# **Random forest and feature importance**"""

from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred_lr)
sns.heatmap(cm,annot=True,fmt='d',cmap='Blues')
plt.title('Confusion Matrix (Logistic Regression)')
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.show()

from sklearn.ensemble import RandomForestClassifier

rf_model=RandomForestClassifier(n_estimators=100,random_state=42)
rf_model.fit(X_train_scaled,y_train)
y_pred_rf= rf_model.predict(X_test_scaled)

print("Random Forest Accuracy:",accuracy_score(y_test, y_pred_rf))

"""Feature importance

"""

# Get feature names after preprocessing
feature_names = preprocessor.get_feature_names_out()

# Feature importances
feat_imp = pd.Series(rf_model.feature_importances_, index=feature_names)
feat_imp.nlargest(10).plot(kind='barh')
plt.title("Random Forest Feature Importance")
plt.show()

"""Save the model

# User upload and prediction
"""

from google.colab import files
files.upload()

import pandas as pd

df = pd.read_csv("heart_dataset.csv")
print(df.columns)  # this will show all column names

numeric_cols = ['age','trestbps','chol','thalch','oldpeak','ca']
categorical_cols = ['sex','cp','fbs','restecg','exang','slope','thal']

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numeric_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
])

pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(n_estimators=100, random_state=42))
])

pipeline.fit(X, y)

import joblib

joblib.dump(pipeline, "heart_pipeline.pkl")
print("✅ Saved pipeline with scaler + model as heart_pipeline.pkl")

X.head(1).to_csv("Heart_user_template.csv", index=False)
print("User template saved as 'Heart_user_template.csv'")

# Install required packages (run once)
!pip install streamlit pyngrok --quiet

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import joblib
# import matplotlib.pyplot as plt
# import seaborn as sns
# 
# # -----------------------------
# # Load trained pipeline & dataset
# # -----------------------------
# pipeline = joblib.load("heart_pipeline.pkl")
# df = pd.read_csv("heart_dataset.csv")
# 
# # -----------------------------
# # Custom CSS for Website Styling
# # -----------------------------
# st.markdown(
#     """
#     <style>
#     body {
#         background-color: #fdfdfd;
#         font-family: 'Segoe UI', sans-serif;
#     }
#     /* Navbar */
#     .navbar {
#         background-color: #ff4b4b;
#         padding: 15px 30px;
#         display: flex;
#         justify-content: space-between;
#         align-items: center;
#         color: white;
#         position: fixed;
#         top: 0;
#         left: 0;
#         width: 100%;
#         z-index: 1000;
#         border-radius: 0px 0px 12px 12px;
#     }
#     .navbar h1 {
#         font-size: 22px;
#         margin: 0;
#         font-weight: bold;
#         display: flex;
#         align-items: center;
#     }
#     .navbar img {
#         height: 30px;
#         margin-right: 10px;
#     }
#     .navbar a {
#         color: white;
#         text-decoration: none;
#         margin-left: 20px;
#         font-weight: 500;
#     }
#     .navbar a:hover {
#         text-decoration: underline;
#     }
#     /* Footer */
#     .footer {
#         position: fixed;
#         bottom: 0;
#         left: 0;
#         width: 100%;
#         padding: 12px;
#         background-color: #ff4b4b;
#         color: white;
#         text-align: center;
#         border-radius: 12px 12px 0px 0px;
#         z-index: 1000;
#     }
#     /* Section padding */
#     .main {
#         padding-top: 90px;  /* space for navbar */
#         padding-bottom: 70px; /* space for footer */
#     }
#     </style>
#     """,
#     unsafe_allow_html=True
# )
# 
# # -----------------------------
# # Navbar (Top Header with Logo)
# # -----------------------------
# st.markdown(
#     """
#     <div class="navbar">
#         <h1><img src="https://cdn-icons-png.flaticon.com/512/3774/3774299.png"> Heart Disease Prediction</h1>
#         <div>
#             <a href="#home">Home</a>
#             <a href="#prediction">Prediction</a>
#             <a href="#analysis">Analysis</a>
#             <a href="#contact">Contact</a>
#         </div>
#     </div>
#     """,
#     unsafe_allow_html=True
# )
# 
# # -----------------------------
# # Sidebar Navigation
# # -----------------------------
# tab = st.sidebar.radio("📌 Navigate", ["🏠 Home", "🩺 Prediction", "📊 Analysis", "📞 Contact"])
# 
# # -----------------------------
# # Home Section with Split Layout
# # -----------------------------
# if tab == "🏠 Home":
#     st.markdown('<div id="home"></div>', unsafe_allow_html=True)
#     col1, col2 = st.columns([1,2])
#     with col1:
#         st.image("https://cdn-icons-png.flaticon.com/512/3774/3774299.png", width=220)
#     with col2:
#         st.header("Welcome to the Heart Disease Prediction Dashboard")
#         st.write("""
#             This interactive web application uses **Machine Learning** to analyze
#             patient health details and predict the risk of heart disease.
# 
#             ### Features:
#             - 🩺 **Prediction Tool** – Enter patient details and check risk
#             - 📊 **Analysis Dashboard** – Explore dataset insights
#             - 📈 **Visual Reports** – Health parameters analysis
#         """)
#         st.success("🔬 Developed with Python + Streamlit")
# 
# # -----------------------------
# # Prediction Section
# # -----------------------------
# elif tab == "🩺 Prediction":
#     st.markdown('<div id="prediction"></div>', unsafe_allow_html=True)
#     col1, col2 = st.columns([1,2])
#     with col1:
#         st.image("https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.vecteezy.com%2Fsystem%2Fresources%2Fpreviews%2F035%2F060%2F354%2Fnon_2x%2Fflat-illustration-a-cardiologist-holding-a-large-magnifying-glass-and-studying-the-health-of-the-heart-vector.jpg&tbnid=JlqqaXudeK-OAM&vet=10CAoQxiAoBGoXChMIuJGk0bLNjwMVAAAAAB0AAAAAEAc..i&imgrefurl=https%3A%2F%2Fwww.vecteezy.com%2Fvector-art%2F35060354-flat-vector-illustration-a-cardiologist-holding-a-large-magnifying-glass-and-studying-the-health-of-the-heart&docid=wj_hMB4zTRVxKM&w=980&h=980&itg=1&q=HEART%20DISEASE%20IMAGE%20ANIMATION&ved=0CAoQxiAoBGoXChMIuJGk0bLNjwMVAAAAAB0AAAAAEAc", width=250)
#     with col2:
#         st.header("🩺 Enter Patient Details")
#         user_input = {
#             "age": st.number_input("Age", min_value=1, max_value=120, value=46),
#             "trestbps": st.number_input("Resting Blood Pressure (trestbps)", value=120),
#             "chol": st.number_input("Cholesterol (chol)", value=200),
#             "thalch": st.number_input("Max Heart Rate Achieved (thalch)", value=150),
#             "oldpeak": st.number_input("ST Depression (oldpeak)", value=1.0),
#             "ca": st.number_input("Number of Major Vessels (ca)", min_value=0, max_value=4, value=0),
#             "sex": st.selectbox("Sex", ["Male", "Female"]),
#             "cp": st.selectbox("Chest Pain Type (cp)", ["typical angina", "atypical angina", "non-anginal", "asymptomatic"]),
#             "fbs": st.selectbox("Fasting Blood Sugar > 120 mg/dl (fbs)", [0, 1]),
#             "restecg": st.selectbox("Resting ECG (restecg)", ["normal", "ST-T wave abnormality", "left ventricular hypertrophy"]),
#             "exang": st.selectbox("Exercise Induced Angina (exang)", [0, 1]),
#             "slope": st.selectbox("Slope of Peak Exercise ST (slope)", ["upsloping", "flat", "downsloping"]),
#             "thal": st.selectbox("Thalassemia (thal)", ["normal", "fixed defect", "reversible defect"])
#         }
# 
#         user_input_df = pd.DataFrame([user_input])
#         categorical_cols = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'thal']
#         for col in categorical_cols:
#             user_input_df[col] = user_input_df[col].astype(str).str.lower()
# 
#         if st.button("🔍 Predict Risk"):
#             prediction = pipeline.predict(user_input_df)[0]
#             if prediction == 1:
#                 st.error("⚠️ High risk of heart disease")
#             else:
#                 st.success("✅ Low risk of heart disease")
# 
# # -----------------------------
# # Analysis Section
# # -----------------------------
# elif tab == "📊 Analysis":
#     st.markdown('<div id="analysis"></div>', unsafe_allow_html=True)
#     st.header("📊 Comparative Analysis")
#     numeric_cols = ['age','trestbps','chol','thalch','oldpeak','ca']
#     categorical_cols = ['sex','cp','fbs','restecg','exang','slope','thal']
# 
#     st.subheader("Dataset Overview")
#     st.dataframe(df.head())
# 
#     st.subheader("📈 Numeric Feature Distributions")
#     fig, axes = plt.subplots(2, 3, figsize=(15, 8))
#     axes = axes.ravel()
#     for i, col in enumerate(numeric_cols):
#         sns.histplot(df[col], kde=True, ax=axes[i], color='skyblue')
#         axes[i].set_title(col)
#     plt.tight_layout()
#     st.pyplot(fig)
# 
#     st.subheader("🗂️ Categorical Feature Distributions")
#     fig, axes = plt.subplots(3, 3, figsize=(15, 12))
#     axes = axes.ravel()
#     for i, col in enumerate(categorical_cols):
#         if col in df.columns:
#             sns.countplot(x=col, data=df, ax=axes[i], palette='pastel')
#             axes[i].set_title(col)
#     plt.tight_layout()
#     st.pyplot(fig)
# 
# # -----------------------------
# # Contact Section
# # -----------------------------
# elif tab == "📞 Contact":
#     st.markdown('<div id="contact"></div>', unsafe_allow_html=True)
#     col1, col2 = st.columns([1,2])
#     with col1:
#         st.image("https://cdn-icons-png.flaticon.com/512/1034/1034159.png", width=220)
#     with col2:
#         st.header("📞 Contact Us")
#         st.write("""
#             💡 Have questions or feedback? Reach out!
#             - 📧 Email: **tamanna@example.com**
#             - 🔗 LinkedIn: [Tamanna](https://linkedin.com)
#             - 🏫 Project: CSE Final Year
#         """)
# 
# # -----------------------------
# # Footer
# # -----------------------------
# st.markdown('<div class="footer">Made with ❤️ by Tamanna | CSE Project</div>', unsafe_allow_html=True)
#

# --- Colab ngrok setup ---
from pyngrok import ngrok,conf
ngrok.kill()  # kills all active tunnels


# Set your ngrok auth token (replace with your token)
conf.get_default().auth_token = "32NKZ0n2h9IJOe3zW16rgwdAsre_79mT6XrgA4hx9chqbcSi9"

# Open a new tunnel to the Streamlit app port
# Use the alternative syntax passing the port as the first argument
public_url = ngrok.connect(8501)
print("🚀 Streamlit app is live at:", public_url)

# Run Streamlit app
!streamlit run app.py &>/dev/null&